<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CochesSeeder extends Seeder
{
    public function run(): void
    {
        $coches = [
            // ── LAMBORGHINI ──────────────────────────────────────────────────
            ['id'=>25,'modelo'=>'Lamborghini Veneno Roadster','anio'=>2013,'precio'=>8527000.00,'descripcion'=>'El Lamborghini Veneno Roadster es un superdeportivo descapotable ultraexclusivo (9 unidades) de 2014, diseñado para un rendimiento extremo en pista pero legal en calle. Logrando 0-100 km/h en 2.9 s y 355 km/h.','marca_id'=>4,'potencia'=>750,'par_motor'=>690,'velocidad_max'=>355,'aceleracion'=>2.9,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Cabrio','color'=>'Rosso Veneno','disponible'=>true,'destacado'=>true],
            ['id'=>26,'modelo'=>'Lamborghini Huracán Performante','anio'=>2017,'precio'=>280000.00,'descripcion'=>'El Lamborghini Huracán Performante es una versión aligerada y potenciada del superdeportivo V10, diseñada para la máxima eficiencia en circuito. Incorpora un motor 5.2L V10 con 640 CV, alcanzando 0-100 km/h en 2,9 segundos. Destaca por su sistema de aerodinámica activa (ALA) y el uso de Forged Composites para reducir peso.','marca_id'=>4,'potencia'=>640,'par_motor'=>600,'velocidad_max'=>325,'aceleracion'=>2.9,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Arancio Anthaeus','disponible'=>true,'destacado'=>false],
            ['id'=>27,'modelo'=>'Lamborghini Aventador SVJ Roadster','anio'=>2019,'precio'=>1300000.00,'descripcion'=>'El Lamborghini Aventador SVJ Roadster es un superdeportivo descapotable de producción limitada (800 unidades) que combina un motor V12 atmosférico de 6.5 litros con 770 CV y 720 Nm de par. Acelera de 0 a 100 km/h en 2,9 segundos y supera los 350 km/h, destacando por su aerodinámica activa ALA 2.0 y techo de fibra de carbono desmontable.','marca_id'=>4,'potencia'=>770,'par_motor'=>720,'velocidad_max'=>350,'aceleracion'=>2.9,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Cabrio','color'=>'Bronzo Zenas','disponible'=>true,'destacado'=>false],
            ['id'=>28,'modelo'=>'Lamborghini Revuelto','anio'=>2023,'precio'=>573327.00,'descripcion'=>'El Lamborghini Revuelto es un superdeportivo híbrido enchufable (HPEV) de alto rendimiento, sucesor del Aventador, con 1.015 CV y velocidad punta superior a 350 km/h. Combina un motor V12 atmosférico de 6.5L con tres motores eléctricos, logrando una aceleración de 0 a 100 km/h en 2,5 segundos.','marca_id'=>4,'potencia'=>1015,'par_motor'=>725,'velocidad_max'=>350,'aceleracion'=>2.5,'combustible'=>'Híbrido','transmision'=>'Automática','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Arancio Apodis','disponible'=>true,'destacado'=>false],
            ['id'=>29,'modelo'=>'Lamborghini Urus Performante','anio'=>2022,'precio'=>300000.00,'descripcion'=>'El Lamborghini Urus Performante es un Super SUV enfocado en las máximas prestaciones, elevando al Urus estándar con más potencia (666 CV), menor peso gracias a la fibra de carbono y un diseño más aerodinámico.','marca_id'=>4,'potencia'=>666,'par_motor'=>850,'velocidad_max'=>306,'aceleracion'=>3.3,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'AWD','num_plazas'=>5,'num_puertas'=>4,'tipo_carroceria'=>'SUV','color'=>'Giallo Auge','disponible'=>true,'destacado'=>false],
            ['id'=>30,'modelo'=>'Lamborghini Murciélago','anio'=>2001,'precio'=>300000.00,'descripcion'=>'El Lamborghini Murciélago es un superdeportivo V12 de alto rendimiento, fabricado entre 2001 y 2010 como el buque insignia de la marca. Destaca por su diseño agresivo con puertas de tijera, motor central, tracción total y carrocería de fibra de carbono.','marca_id'=>4,'potencia'=>640,'par_motor'=>660,'velocidad_max'=>340,'aceleracion'=>3.4,'combustible'=>'Gasolina','transmision'=>'Manual / Automática','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Grigio Telesto','disponible'=>true,'destacado'=>false],

            // ── BMW ──────────────────────────────────────────────────────────
            ['id'=>31,'modelo'=>'BMW M4 GT3','anio'=>2021,'precio'=>415000.00,'descripcion'=>'El BMW M4 GT3 es un vehículo de competición de alto rendimiento diseñado para equipos cliente, basado en el BMW M4 Competition Coupé (G82). Cuenta con un motor S58 de 3.0 litros y 6 cilindros en línea TwinPower Turbo que produce hasta 590 CV.','marca_id'=>8,'potencia'=>590,'par_motor'=>700,'velocidad_max'=>290,'aceleracion'=>3.0,'combustible'=>'Gasolina','transmision'=>'Secuencial','traccion'=>'RWD','num_plazas'=>1,'num_puertas'=>2,'tipo_carroceria'=>'Coupé (Competición)','color'=>'BMW Motorsport Livery','disponible'=>true,'destacado'=>true],
            ['id'=>32,'modelo'=>'BMW M4 Coupé Competition','anio'=>2014,'precio'=>135000.00,'descripcion'=>'El BMW M4 Coupé Competition es un deportivo de alto rendimiento (G82) destacado por su motor 3.0L biturbo de 6 cilindros en línea, que genera 510 CV (375 kW) y 650 Nm de par, alcanzando los 100 km/h en 3.9 segundos.','marca_id'=>8,'potencia'=>510,'par_motor'=>650,'velocidad_max'=>250,'aceleracion'=>3.9,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'RWD / AWD','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Sao Paulo Yellow','disponible'=>true,'destacado'=>false],
            ['id'=>33,'modelo'=>'BMW M3 Sport Evolution','anio'=>1990,'precio'=>300000.00,'descripcion'=>'El BMW M3 Sport Evolution (Evo III), lanzado en 1990, es la versión definitiva y más potente del M3 E30, limitada a 600 unidades para homologación de competición. Cuenta con un motor 2.5 L atmosférico de cuatro cilindros que produce 238 CV.','marca_id'=>8,'potencia'=>238,'par_motor'=>240,'velocidad_max'=>248,'aceleracion'=>6.7,'combustible'=>'Gasolina','transmision'=>'Manual','traccion'=>'RWD','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Jet Black','disponible'=>true,'destacado'=>false],
            ['id'=>34,'modelo'=>'BMW M3 CS','anio'=>2024,'precio'=>177000.00,'descripcion'=>'El BMW M3 CS (2024) es una edición limitada de alto rendimiento que combina la practicidad de una berlina con un rendimiento de circuito. Incorpora un motor 3.0L biturbo de 6 cilindros en línea que entrega 550 CV y 650 Nm, tracción total M xDrive.','marca_id'=>8,'potencia'=>550,'par_motor'=>650,'velocidad_max'=>302,'aceleracion'=>3.4,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'AWD','num_plazas'=>5,'num_puertas'=>4,'tipo_carroceria'=>'Berlina','color'=>'Signal Green','disponible'=>true,'destacado'=>false],
            ['id'=>35,'modelo'=>'BMW M5 CS','anio'=>2022,'precio'=>207300.00,'descripcion'=>'El BMW M5 CS (Competition Sport) es el sedán de producción más potente y rápido en la historia de BMW, lanzado como una edición limitada con un motor 4.4L V8 TwinPower Turbo que produce 635 CV y 750 Nm de par.','marca_id'=>8,'potencia'=>635,'par_motor'=>750,'velocidad_max'=>305,'aceleracion'=>3.0,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'AWD','num_plazas'=>4,'num_puertas'=>4,'tipo_carroceria'=>'Berlina','color'=>'Frozen Deep Green','disponible'=>true,'destacado'=>false],
            ['id'=>36,'modelo'=>'BMW M2','anio'=>2025,'precio'=>97000.00,'descripcion'=>'El BMW M2 es un deportivo compacto de altas prestaciones (G87), enfocado en la conducción pura con tracción trasera, motor 6 cilindros biturbo en línea que genera hasta 460 CV. Disponible con caja manual o automática de 8 velocidades.','marca_id'=>8,'potencia'=>460,'par_motor'=>550,'velocidad_max'=>250,'aceleracion'=>4.1,'combustible'=>'Gasolina','transmision'=>'Automática / Manual','traccion'=>'RWD','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Zandvoort Blue','disponible'=>true,'destacado'=>false],

            // ── McLAREN ──────────────────────────────────────────────────────
            ['id'=>37,'modelo'=>'McLaren Senna','anio'=>2017,'precio'=>1700000.00,'descripcion'=>'El McLaren Senna es un hiperdeportivo enfocado en circuitos y homologado para calle, caracterizado por su enfoque radical en el bajo peso y la aerodinámica. Equipado con un motor V8 biturbo de 4.0L que genera 800 CV y 800 Nm de par.','marca_id'=>9,'potencia'=>800,'par_motor'=>800,'velocidad_max'=>335,'aceleracion'=>2.8,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Victory Grey','disponible'=>true,'destacado'=>true],
            ['id'=>38,'modelo'=>'McLaren 765LT','anio'=>2020,'precio'=>545000.00,'descripcion'=>'El McLaren 765LT es un superdeportivo de edición limitada enfocado en la pista, sucesor de la línea Longtail. Equipado con un motor V8 biturbo de 4.0 litros, genera 765 CV y 800 Nm de par, logrando una aceleración de 0 a 100 km/h en solo 2,8 segundos.','marca_id'=>9,'potencia'=>765,'par_motor'=>800,'velocidad_max'=>330,'aceleracion'=>2.8,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Nardo Orange','disponible'=>true,'destacado'=>false],
            ['id'=>39,'modelo'=>'McLaren F1','anio'=>1992,'precio'=>25000000.00,'descripcion'=>'El McLaren F1 (1992) es un superdeportivo histórico diseñado por Gordon Murray como el deportivo definitivo, destacando por su chasis de fibra de carbono, posición central del conductor para tres plazas y un motor V12 atmosférico de 6.1L que produce 627 CV.','marca_id'=>9,'potencia'=>916,'par_motor'=>900,'velocidad_max'=>350,'aceleracion'=>2.8,'combustible'=>'Híbrido','transmision'=>'Automática','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Volcano Yellow','disponible'=>true,'destacado'=>false],
            ['id'=>40,'modelo'=>'McLaren 720S','anio'=>2018,'precio'=>300000.00,'descripcion'=>'El McLaren 720S es un superdeportivo biplaza de alto rendimiento, presentado en 2017, equipado con un motor 4.0L V8 biturbo que genera 720 CV y 770 Nm de par. Alcanza los 100 km/h en solo 2,8-2,9 segundos y una velocidad punta de 341 km/h.','marca_id'=>9,'potencia'=>720,'par_motor'=>770,'velocidad_max'=>341,'aceleracion'=>2.9,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Azores Orange','disponible'=>true,'destacado'=>false],
            ['id'=>41,'modelo'=>'McLaren 675LT','anio'=>2016,'precio'=>420000.00,'descripcion'=>'El McLaren 675LT es un superdeportivo de edición limitada (500 coupés/500 spiders) presentado en 2015, diseñado para la máxima ligereza, aerodinámica y rendimiento en pista. Monta un motor 3.8L V8 Biturbo de 675 CV y 700 Nm.','marca_id'=>9,'potencia'=>675,'par_motor'=>700,'velocidad_max'=>330,'aceleracion'=>2.9,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Napier Green','disponible'=>true,'destacado'=>false],
            ['id'=>42,'modelo'=>'McLaren P1 GTR','anio'=>2015,'precio'=>3000000.00,'descripcion'=>'El McLaren P1 GTR es una versión de circuito extrema del hiperdeportivo híbrido P1, diseñada sin restricciones legales. Cuenta con 1.000 CV, un peso reducido y aerodinámica optimizada, incluyendo un alerón trasero fijo con sistema DRS.','marca_id'=>9,'potencia'=>1000,'par_motor'=>1000,'velocidad_max'=>362,'aceleracion'=>2.4,'combustible'=>'Híbrido','transmision'=>'Automática','traccion'=>'RWD','num_plazas'=>1,'num_puertas'=>2,'tipo_carroceria'=>'Coupé (Circuito)','color'=>'Lark Livery','disponible'=>true,'destacado'=>false],
            ['id'=>43,'modelo'=>'McLaren P1','anio'=>2014,'precio'=>2152450.00,'descripcion'=>'El McLaren P1 es un hiperdeportivo híbrido enchufable de edición limitada (375 unidades), producido entre 2013 y 2015, diseñado como sucesor del McLaren F1. Combina un motor V8 biturbo de 3.8L con un motor eléctrico para lograr 916 CV.','marca_id'=>9,'potencia'=>916,'par_motor'=>900,'velocidad_max'=>350,'aceleracion'=>2.8,'combustible'=>'Híbrido','transmision'=>'Automática','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Volcano Yellow','disponible'=>true,'destacado'=>false],
            ['id'=>44,'modelo'=>'McLaren 600LT','anio'=>2019,'precio'=>290000.00,'descripcion'=>'El McLaren 600LT (Longtail) es un superdeportivo homologado para carretera enfocado en la pista, caracterizado por su ligereza, aerodinámica avanzada y un motor V8 biturbo de 3.8L que rinde 600 CV y 620 Nm de par.','marca_id'=>9,'potencia'=>600,'par_motor'=>620,'velocidad_max'=>328,'aceleracion'=>2.9,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Chicane Effect','disponible'=>true,'destacado'=>false],

            // ── PORSCHE ──────────────────────────────────────────────────────
            ['id'=>45,'modelo'=>'Porsche 911 GT3 RS','anio'=>2019,'precio'=>286000.00,'descripcion'=>'El Porsche 911 GT3 es un automóvil deportivo cupé de dos puertas, con motor plano de seis cilindros en disposición trasera montado longitudinalmente y de tracción trasera. Se trata de una versión más radical del 911 estándar con motor naturalmente aspirado.','marca_id'=>10,'potencia'=>525,'par_motor'=>465,'velocidad_max'=>296,'aceleracion'=>3.2,'combustible'=>'Gasolina','transmision'=>'Automática (PDK)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Pyro Red','disponible'=>true,'destacado'=>true],
            ['id'=>46,'modelo'=>'Porsche 911 964 Turbo','anio'=>1994,'precio'=>240000.00,'descripcion'=>'El Porsche 911 (964) Turbo, producido entre 1990 y 1994, es un icónico deportivo de motor trasero y tracción trasera, conocido por su carrocería ancha, alerón fijo distintivo y un motor bóxer de 6 cilindros sobrealimentado de 3.6L (360 CV).','marca_id'=>10,'potencia'=>360,'par_motor'=>520,'velocidad_max'=>280,'aceleracion'=>4.8,'combustible'=>'Gasolina','transmision'=>'Manual','traccion'=>'RWD','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Midnight Blue Metallic','disponible'=>true,'destacado'=>false],
            ['id'=>47,'modelo'=>'Porsche 718 Cayman GT4 RS','anio'=>2021,'precio'=>200000.00,'descripcion'=>'El Porsche 718 Cayman GT4 RS es la versión de alto rendimiento definitiva de la gama 718, diseñada para la máxima ligereza y agilidad. Monta un motor atmosférico bóxer de 4.0 litros y 6 cilindros central con 500 CV.','marca_id'=>10,'potencia'=>500,'par_motor'=>450,'velocidad_max'=>315,'aceleracion'=>3.4,'combustible'=>'Gasolina','transmision'=>'Automática (PDK)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Arctic Grey','disponible'=>true,'destacado'=>false],
            ['id'=>48,'modelo'=>'Porsche 935','anio'=>2019,'precio'=>1450000.00,'descripcion'=>'El Porsche 935 es un icónico automóvil de carreras derivado del 911 Turbo (930), diseñado para el Grupo 5 de la FIA entre 1976 y 1984. Dominó la resistencia mundial con más de 150 victorias, incluyendo las 24 Horas de Le Mans de 1979.','marca_id'=>10,'potencia'=>500,'par_motor'=>750,'velocidad_max'=>340,'aceleracion'=>2.7,'combustible'=>'Gasolina','transmision'=>'Automática (PDK)','traccion'=>'RWD','num_plazas'=>1,'num_puertas'=>2,'tipo_carroceria'=>'Coupé (Circuito)','color'=>'Martini Livery','disponible'=>true,'destacado'=>false],
            ['id'=>49,'modelo'=>'Porsche 918 Spyder','anio'=>2015,'precio'=>1800000.00,'descripcion'=>'El Porsche 918 Spyder es un superdeportivo híbrido enchufable de producción limitada (918 unidades, 2013-2015), que combina un motor 4.6L V8 gasolina con dos motores eléctricos, alcanzando 887 CV y tracción total.','marca_id'=>10,'potencia'=>887,'par_motor'=>1280,'velocidad_max'=>345,'aceleracion'=>2.6,'combustible'=>'Híbrido','transmision'=>'Automática (PDK)','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Cabrio','color'=>'Liquid Metal Silver','disponible'=>true,'destacado'=>false],
            ['id'=>50,'modelo'=>'Porsche Carrera GT','anio'=>2004,'precio'=>1500000.00,'descripcion'=>'El Porsche Carrera GT es un superdeportivo analógico icónico con motor central V10 de 5.7 litros y 612 CV, diseñado para competición y adaptado a la calle. Destaca por su chasis monocasco de fibra de carbono y transmisión manual de 6 velocidades.','marca_id'=>10,'potencia'=>612,'par_motor'=>590,'velocidad_max'=>330,'aceleracion'=>3.9,'combustible'=>'Gasolina','transmision'=>'Manual','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Cabrio / Targa','color'=>'GT Silver Metallic','disponible'=>true,'destacado'=>false],

            // ── AUDI ─────────────────────────────────────────────────────────
            ['id'=>51,'modelo'=>'Audi R8 Coupé V10 GT AWD','anio'=>2023,'precio'=>250000.00,'descripcion'=>'El Audi R8 Coupé V10 GT es una edición limitada (333 unidades) que representa el cierre del icónico motor V10 atmosférico de 5.2 litros, ofreciendo 620 CV. La versión GT 2023 se enfoca en tracción trasera (RWD) y alto rendimiento.','marca_id'=>11,'potencia'=>620,'par_motor'=>565,'velocidad_max'=>320,'aceleracion'=>3.4,'combustible'=>'Gasolina','transmision'=>'Automática (S tronic)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Suzuka Gray','disponible'=>true,'destacado'=>true],
            ['id'=>52,'modelo'=>'Audi TT Coupé','anio'=>2015,'precio'=>72800.00,'descripcion'=>'El Audi TT Coupé es un deportivo compacto icónico, conocido por su diseño de líneas puras y fluidas, que equilibra deportividad y uso diario. Destaca por su tecnología avanzada, incluyendo el Audi virtual cockpit.','marca_id'=>11,'potencia'=>245,'par_motor'=>370,'velocidad_max'=>250,'aceleracion'=>5.8,'combustible'=>'Gasolina','transmision'=>'Automática (S tronic)','traccion'=>'AWD (quattro)','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Turbo Blue','disponible'=>true,'destacado'=>false],
            ['id'=>53,'modelo'=>'Audi RS6 Avant','anio'=>2020,'precio'=>151770.00,'descripcion'=>'El Audi RS 6 Avant es un familiar de altísimo rendimiento, que combina la practicidad de un coche familiar con prestaciones de superdeportivo. Equipado con un motor 4.0 TFSI V8 biturbo, entrega hasta 630 CV y 850 Nm de par.','marca_id'=>11,'potencia'=>600,'par_motor'=>800,'velocidad_max'=>250,'aceleracion'=>3.6,'combustible'=>'Gasolina (MHEV)','transmision'=>'Automática (Tiptronic)','traccion'=>'AWD (quattro)','num_plazas'=>5,'num_puertas'=>5,'tipo_carroceria'=>'Familiar (Avant)','color'=>'Sebring Black','disponible'=>true,'destacado'=>false],
            ['id'=>54,'modelo'=>'Audi RS5 Berlina','anio'=>2026,'precio'=>125900.00,'descripcion'=>'El nuevo Audi RS 5 (2026) es una berlina deportiva híbrida enchufable (PHEV) de alto rendimiento, que combina un motor 2.9 V6 biturbo con un motor eléctrico para lograr una potencia total de 639 CV y tracción quattro.','marca_id'=>11,'potencia'=>450,'par_motor'=>600,'velocidad_max'=>250,'aceleracion'=>3.9,'combustible'=>'Gasolina','transmision'=>'Automática (Tiptronic)','traccion'=>'AWD (quattro)','num_plazas'=>5,'num_puertas'=>4,'tipo_carroceria'=>'Berlina / Sportback','color'=>'Nardo Gray','disponible'=>true,'destacado'=>false],
            ['id'=>55,'modelo'=>'Audi RS7 Sportback Berlina','anio'=>2013,'precio'=>161950.00,'descripcion'=>'El Audi RS7 Sportback (berlina coupé de 4 puertas) es un vehículo de altísimo rendimiento con un motor 4.0 V8 biturbo que entrega entre 600 CV y 800 Nm de par. Destaca por su diseño agresivo y aceleración de 0 a 100 km/h en 3,4-3,6 segundos.','marca_id'=>11,'potencia'=>600,'par_motor'=>800,'velocidad_max'=>250,'aceleracion'=>3.6,'combustible'=>'Gasolina (MHEV)','transmision'=>'Automática (Tiptronic)','traccion'=>'AWD (quattro)','num_plazas'=>5,'num_puertas'=>4,'tipo_carroceria'=>'Berlina / Sportback','color'=>'Tango Red','disponible'=>true,'destacado'=>false],
            ['id'=>56,'modelo'=>'Audi S8 US Version','anio'=>2022,'precio'=>113704.00,'descripcion'=>'El Audi S8 (versión estadounidense) es la máxima expresión del sedán de lujo de alto rendimiento de la marca alemana, combinando un diseño discreto pero imponente con tecnología punta y mecánica de alto rendimiento.','marca_id'=>11,'potencia'=>571,'par_motor'=>800,'velocidad_max'=>250,'aceleracion'=>3.8,'combustible'=>'Gasolina (MHEV)','transmision'=>'Automática (Tiptronic)','traccion'=>'AWD (quattro)','num_plazas'=>5,'num_puertas'=>4,'tipo_carroceria'=>'Berlina','color'=>'Daytona Gray','disponible'=>true,'destacado'=>false],

            // ── PAGANI ───────────────────────────────────────────────────────
            ['id'=>57,'modelo'=>'Pagani Zonda R','anio'=>2007,'precio'=>8657000.00,'descripcion'=>'El Pagani Zonda R es un hiperdeportivo de circuito, extremo y exclusivo, presentado en 2007, del cual solo se fabricaron 15 unidades. Destaca por su motor Mercedes-AMG 6.0L V12 de 750 CV, un peso ligero de 1.100 kg.','marca_id'=>12,'potencia'=>750,'par_motor'=>710,'velocidad_max'=>351,'aceleracion'=>2.7,'combustible'=>'Gasolina','transmision'=>'Secuencial (6 vel.)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé (Circuito)','color'=>'Carbono Visto','disponible'=>true,'destacado'=>true],
            ['id'=>58,'modelo'=>'Pagani Huayra R','anio'=>2021,'precio'=>2600000.00,'descripcion'=>'El Pagani Huayra R es un hiperdeportivo exclusivo para circuito, concebido como la máxima expresión de rendimiento y arte automotriz de la marca. Equipado con un motor V12 atmosférico de 6.0 litros (desarrollado por HWA) que produce 850 CV a 9000 rpm.','marca_id'=>12,'potencia'=>850,'par_motor'=>750,'velocidad_max'=>380,'aceleracion'=>2.7,'combustible'=>'Gasolina','transmision'=>'Secuencial (6 vel.)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé (Circuito)','color'=>'Carbon Fiber / Silver','disponible'=>true,'destacado'=>false],
            ['id'=>59,'modelo'=>'Pagani Utopia','anio'=>2023,'precio'=>3000000.00,'descripcion'=>'El Pagani Utopia es un hiperdeportivo artesanal, sucesor del Huayra, enfocado en la ligereza, la pureza analógica y el diseño artístico. Monta un motor V12 biturbo de 6.0 litros desarrollado por Mercedes-AMG que produce 864 CV.','marca_id'=>12,'potencia'=>864,'par_motor'=>1100,'velocidad_max'=>354,'aceleracion'=>3.1,'combustible'=>'Gasolina','transmision'=>'Manual / Automática','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Rinascimento','disponible'=>true,'destacado'=>false],
            ['id'=>60,'modelo'=>'Pagani Imola','anio'=>2021,'precio'=>5000000.00,'descripcion'=>'El Pagani Imola es un hiperdeportivo extremo y ultra exclusivo, limitado a solo 5 unidades coupé, diseñado para un rendimiento máximo en pista pero homologado para calle. Desarrollado en el circuito de Imola.','marca_id'=>12,'potencia'=>827,'par_motor'=>1100,'velocidad_max'=>350,'aceleracion'=>2.8,'combustible'=>'Gasolina','transmision'=>'Automática (Xtrac 7 vel.)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Imola Grey','disponible'=>true,'destacado'=>false],
            ['id'=>61,'modelo'=>'Pagani Zonda Revolucion','anio'=>2013,'precio'=>2200000.00,'descripcion'=>'El Pagani Zonda Revolución es la cúspide final del legendario superdeportivo, limitado a solo 5 unidades. Diseñado para la pista, combina un chasis de fibra de carbono y titanio con un motor Mercedes-AMG V12 de 6.0L que produce 800 CV.','marca_id'=>12,'potencia'=>800,'par_motor'=>730,'velocidad_max'=>350,'aceleracion'=>2.6,'combustible'=>'Gasolina','transmision'=>'Secuencial (6 vel.)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé (Circuito)','color'=>'Blue Carbon Fiber','disponible'=>true,'destacado'=>false],
            ['id'=>62,'modelo'=>'Pagani Huayra BC','anio'=>2016,'precio'=>4000000.00,'descripcion'=>'El Pagani Huayra BC es una versión extrema y ultraligera del hiperdeportivo italiano, limitada a 20 unidades coupé, enfocada en el rendimiento en pista. Utiliza un motor V12 de 6.0 litros biturbo desarrollado por AMG, potenciado a más de 790-800 caballos.','marca_id'=>12,'potencia'=>800,'par_motor'=>1100,'velocidad_max'=>370,'aceleracion'=>3.0,'combustible'=>'Gasolina','transmision'=>'Automática (Xtrac 7 vel.)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Grigio Benny','disponible'=>true,'destacado'=>false],

            // ── FERRARI ──────────────────────────────────────────────────────
            ['id'=>63,'modelo'=>'Ferrari F40','anio'=>1987,'precio'=>3500000.00,'descripcion'=>'El Ferrari F40 (1987-1992) es un superdeportivo icónico, famoso por ser el último aprobado por Enzo Ferrari. Combina un motor V8 biturbo de 2.9L (478 CV) con una carrocería ligera de Kevlar/fibra de carbono, alcanzando 324 km/h.','marca_id'=>13,'potencia'=>478,'par_motor'=>577,'velocidad_max'=>324,'aceleracion'=>4.1,'combustible'=>'Gasolina','transmision'=>'Manual','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Rosso Corsa','disponible'=>true,'destacado'=>false],
            ['id'=>64,'modelo'=>'Ferrari LaFerrari Aperta','anio'=>2017,'precio'=>6000000.00,'descripcion'=>'La Ferrari LaFerrari Aperta (2016) es la versión descapotable del icónico hiperdeportivo híbrido, lanzada para el 70 aniversario de la marca. Mantiene el motor V12 y el sistema eléctrico HY-KERS con una potencia total de 963 CV. Con solo 210 unidades producidas.','marca_id'=>13,'potencia'=>963,'par_motor'=>900,'velocidad_max'=>350,'aceleracion'=>2.8,'combustible'=>'Híbrido','transmision'=>'Automática (Doble embrague 7 vel.)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Cabrio','color'=>'Nero Daytona','disponible'=>true,'destacado'=>false],
            ['id'=>65,'modelo'=>'Ferrari 488 Pista Spider','anio'=>2019,'precio'=>650000.00,'descripcion'=>'El Ferrari 488 Pista Spider es un descapotable de alto rendimiento, edición especial, que combina el motor V8 de 3.9 litros biturbo más potente de la historia de la marca (720 CV) con una experiencia a cielo abierto.','marca_id'=>13,'potencia'=>720,'par_motor'=>770,'velocidad_max'=>340,'aceleracion'=>2.9,'combustible'=>'Gasolina','transmision'=>'Automática (Doble embrague 7 vel.)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Cabrio','color'=>'Blu Nart','disponible'=>true,'destacado'=>false],
            ['id'=>66,'modelo'=>'Ferrari 812 Competizione','anio'=>2021,'precio'=>1400000.00,'descripcion'=>'El Ferrari 812 Competizione es una edición limitada y radical del 812 Superfast, enfocada en la máxima pista, con un motor V12 de 6.5 litros atmosférico que genera 830 CV a 9.250 rpm y alcanza las 9.500 rpm.','marca_id'=>13,'potencia'=>830,'par_motor'=>692,'velocidad_max'=>340,'aceleracion'=>2.9,'combustible'=>'Gasolina','transmision'=>'Automática (Doble embrague 7 vel.)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Grigio Silverstone','disponible'=>true,'destacado'=>true],
            ['id'=>67,'modelo'=>'Ferrari 812 GTS','anio'=>2020,'precio'=>450000.00,'descripcion'=>'El Ferrari 812 GTS es un descapotable de producción con motor V12 delantero de 6.5 litros, que entrega 800 cv y alcanza 340 km/h. Es la variante Spider del 812 Superfast, acelerando de 0 a 100 km/h en menos de 3 segundos.','marca_id'=>13,'potencia'=>800,'par_motor'=>718,'velocidad_max'=>340,'aceleracion'=>3.0,'combustible'=>'Gasolina','transmision'=>'Automática (Doble embrague 7 vel.)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Cabrio','color'=>'Giallo Modena','disponible'=>true,'destacado'=>false],
            ['id'=>68,'modelo'=>'Ferrari 599XX','anio'=>2010,'precio'=>1732760.00,'descripcion'=>'El Ferrari 599XX es un vehículo de pista ultra radical, no homologado para calle, basado en el 599 GTB y parte del programa exclusivo XX. Equipado con un motor V12 de 6.0 litros, produce entre 700 y 750 CV.','marca_id'=>13,'potencia'=>730,'par_motor'=>700,'velocidad_max'=>315,'aceleracion'=>2.9,'combustible'=>'Gasolina','transmision'=>'Secuencial (F1 de 6 vel.)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé (Circuito)','color'=>'Rosso Corsa','disponible'=>true,'destacado'=>false],

            // ── TOYOTA ───────────────────────────────────────────────────────
            ['id'=>69,'modelo'=>'Toyota Supra MK5','anio'=>2019,'precio'=>78000.00,'descripcion'=>'El Toyota Supra MK5 (A90), lanzado en 2019, es un deportivo biplaza de tracción trasera y motor delantero, fruto de la colaboración con BMW. Ofrece motores 2.0L (4 cil.) y 3.0L (6 cil.) turboalimentados, destacando por su agilidad.','marca_id'=>14,'potencia'=>340,'par_motor'=>500,'velocidad_max'=>250,'aceleracion'=>4.3,'combustible'=>'Gasolina','transmision'=>'Automática / Manual','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Horizon Blue','disponible'=>true,'destacado'=>false],
            ['id'=>70,'modelo'=>'Toyota Supra MK4 Hycade Stage 1','anio'=>1996,'precio'=>150000.00,'descripcion'=>'El Toyota Supra MK4 con kit de carrocería Hycade Stage 1 es una reinterpretación digital/física de alto rendimiento que moderniza el clásico A80. Destaca por un estilo de carrocería ancha (widebody) más agresivo y detalles en fibra de carbono.','marca_id'=>14,'potencia'=>330,'par_motor'=>441,'velocidad_max'=>250,'aceleracion'=>5.1,'combustible'=>'Gasolina','transmision'=>'Manual','traccion'=>'RWD','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Renaissance Red','disponible'=>true,'destacado'=>true],
            ['id'=>71,'modelo'=>'Toyota RAV4 TRD Off Road','anio'=>2020,'precio'=>33250.00,'descripcion'=>'La Toyota RAV4 TRD Off-Road fue introducida oficialmente para el año modelo 2020. Esta versión se destaca por su enfoque en la aventura con mejoras específicas en suspensión, neumáticos todoterreno y tracción.','marca_id'=>14,'potencia'=>206,'par_motor'=>249,'velocidad_max'=>200,'aceleracion'=>8.4,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'4x4 (AWD)','num_plazas'=>5,'num_puertas'=>5,'tipo_carroceria'=>'SUV','color'=>'Magnetic Gray Metallic','disponible'=>true,'destacado'=>false],
            ['id'=>72,'modelo'=>'Toyota GT86','anio'=>2017,'precio'=>23000.00,'descripcion'=>'El Toyota GT86 se lanzó al mercado en 2012 y se mantuvo en producción con su primera generación hasta aproximadamente 2020-2021. Fue desarrollado en colaboración con Subaru, compartiendo plataforma con el Subaru BRZ.','marca_id'=>14,'potencia'=>200,'par_motor'=>205,'velocidad_max'=>226,'aceleracion'=>7.6,'combustible'=>'Gasolina','transmision'=>'Manual','traccion'=>'RWD','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Pure Red','disponible'=>true,'destacado'=>false],
            ['id'=>73,'modelo'=>'Toyota Camry','anio'=>2021,'precio'=>52000.00,'descripcion'=>'El Toyota Camry es una berlina sedán de tamaño mediano reconocida por su fiabilidad, confort de marcha y eficiencia, comercializándose actualmente con motorización híbrida autorrecargable (HEV).','marca_id'=>14,'potencia'=>218,'par_motor'=>221,'velocidad_max'=>180,'aceleracion'=>8.3,'combustible'=>'Híbrido','transmision'=>'Automática (e-CVT)','traccion'=>'FWD','num_plazas'=>5,'num_puertas'=>4,'tipo_carroceria'=>'Berlina','color'=>'Platinum White Pearl','disponible'=>true,'destacado'=>false],
            ['id'=>74,'modelo'=>'Toyota Century','anio'=>2018,'precio'=>22527.00,'descripcion'=>'El Toyota Century es el sedán de superlujo definitivo de Japón, conocido como el Rolls-Royce japonés. Desde 1967, representa la máxima sofisticación y discreción para la élite y la Casa Imperial.','marca_id'=>14,'potencia'=>280,'par_motor'=>481,'velocidad_max'=>210,'aceleracion'=>7.5,'combustible'=>'Gasolina','transmision'=>'Automática','traccion'=>'RWD','num_plazas'=>5,'num_puertas'=>4,'tipo_carroceria'=>'Berlina','color'=>'Kamui Black','disponible'=>true,'destacado'=>false],

            // ── NISSAN ───────────────────────────────────────────────────────
            ['id'=>75,'modelo'=>'Nissan GT-R R35','anio'=>2017,'precio'=>111000.00,'descripcion'=>'El Nissan GT-R R35, conocido como Godzilla, es un superdeportivo japonés (cupé 2+2) lanzado en 2007 que revolucionó el mercado por su rendimiento y tecnología. Equipado con un motor V6 biturbo de 3.8L montado a mano.','marca_id'=>15,'potencia'=>570,'par_motor'=>637,'velocidad_max'=>315,'aceleracion'=>2.8,'combustible'=>'Gasolina','transmision'=>'Automática (Doble embrague 6 vel.)','traccion'=>'AWD','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Bayside Blue / Katsura Orange','disponible'=>true,'destacado'=>true],
            ['id'=>76,'modelo'=>'Nissan Skyline GT-R R34','anio'=>1999,'precio'=>162500.00,'descripcion'=>'El Nissan Skyline GT-R R34 (1999-2002) es un deportivo japonés legendario. Destaca por su motor RB26DETT 2.6L biturbo de 6 cilindros en línea, tracción total ATTESA E-TS y avanzada tecnología.','marca_id'=>15,'potencia'=>280,'par_motor'=>353,'velocidad_max'=>250,'aceleracion'=>5.5,'combustible'=>'Gasolina','transmision'=>'Manual','traccion'=>'AWD','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Gun Grey Metallic','disponible'=>true,'destacado'=>false],
            ['id'=>77,'modelo'=>'Nissan 370Z','anio'=>2013,'precio'=>42500.00,'descripcion'=>'El Nissan 370Z es un deportivo biplaza icónico conocido por su diseño compacto, motor atmosférico V6 de 3.7 litros y tracción trasera. Ofrece alrededor de 328-344 CV.','marca_id'=>15,'potencia'=>328,'par_motor'=>363,'velocidad_max'=>250,'aceleracion'=>5.3,'combustible'=>'Gasolina','transmision'=>'Manual / Automática','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Monterey Blue','disponible'=>true,'destacado'=>false],
            ['id'=>78,'modelo'=>'Nissan Silvia S15','anio'=>1999,'precio'=>50000.00,'descripcion'=>'El Nissan Silvia S15 (1999-2002) es la última y más icónica generación de la serie Silvia, un cupé deportivo compacto de tracción trasera conocido por su chasis rígido, diseño agresivo y potencial para el drift.','marca_id'=>15,'potencia'=>250,'par_motor'=>275,'velocidad_max'=>235,'aceleracion'=>5.6,'combustible'=>'Gasolina','transmision'=>'Manual','traccion'=>'RWD','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Lightning Yellow','disponible'=>true,'destacado'=>false],
            ['id'=>79,'modelo'=>'Nissan Skyline GT-R R32','anio'=>1989,'precio'=>70000.00,'descripcion'=>'El Nissan Skyline GT-R R32 (1989-1994) es un icónico deportivo japonés. Equipado con un motor RB26DETT de 2.6L biturbo y tracción integral ATTESA E-TS, entregaba 280 CV de serie.','marca_id'=>15,'potencia'=>280,'par_motor'=>353,'velocidad_max'=>250,'aceleracion'=>5.5,'combustible'=>'Gasolina','transmision'=>'Manual','traccion'=>'AWD','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Gun Grey Metallic','disponible'=>true,'destacado'=>false],
            ['id'=>80,'modelo'=>'Nissan 350Z Z30 Wide Body','anio'=>2002,'precio'=>134000.00,'descripcion'=>'El Nissan 350Z con kit Wide Body (carrocería ancha) es una de las modificaciones más populares y estéticamente agresivas para el deportivo Z33/Z30 de Nissan, a menudo asociado a estilos de tuning JDM, Drift o Rocket Bunny.','marca_id'=>15,'potencia'=>313,'par_motor'=>358,'velocidad_max'=>250,'aceleracion'=>5.7,'combustible'=>'Gasolina','transmision'=>'Manual / Automática','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Sunset Orange','disponible'=>true,'destacado'=>false],

            // ── MERCEDES-BENZ ─────────────────────────────────────────────────
            ['id'=>81,'modelo'=>'Mercedes-Benz AMG GT Black Series','anio'=>2020,'precio'=>600000.00,'descripcion'=>'El Mercedes-Benz AMG GT Black Series (2021) es una edición limitada de alto rendimiento, diseñada para circuito pero homologada para calle, con un motor 4.0L V8 biturbo que desarrolla 730 CV y 800 Nm de par.','marca_id'=>16,'potencia'=>730,'par_motor'=>800,'velocidad_max'=>325,'aceleracion'=>3.2,'combustible'=>'Gasolina','transmision'=>'Automática (AMG SPEEDSHIFT DCT 7G)','traccion'=>'RWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'AMG Magmabeam','disponible'=>true,'destacado'=>true],
            ['id'=>82,'modelo'=>'Mercedes-Benz AMG G63','anio'=>2019,'precio'=>223000.00,'descripcion'=>'El Mercedes-Benz AMG G63 es un todoterreno de lujo de alto rendimiento, reconocido por su icónico diseño cuadrado, motor V8 biturbo de 4.0 litros (585 CV y 850 Nm) y tracción 4MATIC.','marca_id'=>16,'potencia'=>585,'par_motor'=>850,'velocidad_max'=>220,'aceleracion'=>4.5,'combustible'=>'Gasolina','transmision'=>'Automática (AMG SPEEDSHIFT TCT 9G)','traccion'=>'4x4','num_plazas'=>5,'num_puertas'=>5,'tipo_carroceria'=>'SUV','color'=>'Obsidian Black','disponible'=>true,'destacado'=>false],
            ['id'=>83,'modelo'=>'Mercedes-Benz AMG ONE','anio'=>2022,'precio'=>3387950.00,'descripcion'=>'El Mercedes-AMG ONE es un hiperdeportivo híbrido enchufable de producción limitada (275 unidades) que traslada tecnología real de Fórmula 1 a la carretera. Con un motor V6 de 1.6 litros y cuatro motores eléctricos, ofrece una potencia combinada de 1.063 CV.','marca_id'=>16,'potencia'=>1063,'par_motor'=>1000,'velocidad_max'=>352,'aceleracion'=>2.9,'combustible'=>'Híbrido','transmision'=>'Manual Automatizada (7 vel.)','traccion'=>'AWD (4MATIC+)','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Silver Arrows Livery','disponible'=>true,'destacado'=>false],
            ['id'=>84,'modelo'=>'Mercedes-Benz AMG SL 63','anio'=>2008,'precio'=>230000.00,'descripcion'=>'El Mercedes-AMG SL 63 es un descapotable de lujo y alto rendimiento, reinterpretado como un Roadster deportivo de 2+2 plazas con capota de lona. Destaca por su motor V8 biturbo de 4.0 litros, ofreciendo 585 CV.','marca_id'=>16,'potencia'=>585,'par_motor'=>800,'velocidad_max'=>315,'aceleracion'=>3.6,'combustible'=>'Gasolina','transmision'=>'Automática (AMG SPEEDSHIFT MCT 9G)','traccion'=>'AWD (4MATIC+)','num_plazas'=>4,'num_puertas'=>2,'tipo_carroceria'=>'Cabrio','color'=>'Hyper Blue Metallic','disponible'=>true,'destacado'=>false],
            ['id'=>85,'modelo'=>'Mercedes-Benz AMG E63','anio'=>2017,'precio'=>70000.00,'descripcion'=>'El Mercedes-AMG E 63 S 4MATIC+ es una berlina de lujo de alto rendimiento, destacada por su motor 4.0L V8 biturbo que genera hasta 612 CV y 850 Nm de torque. Acelera de 0 a 100 km/h en aproximadamente 3.4 segundos.','marca_id'=>16,'potencia'=>612,'par_motor'=>850,'velocidad_max'=>300,'aceleracion'=>3.4,'combustible'=>'Gasolina','transmision'=>'Automática (AMG SPEEDSHIFT MCT 9G)','traccion'=>'AWD (4MATIC+)','num_plazas'=>5,'num_puertas'=>4,'tipo_carroceria'=>'Berlina','color'=>'Graphite Grey Magno','disponible'=>true,'destacado'=>false],
            ['id'=>86,'modelo'=>'Mercedes-Benz AMG GT63 S E Performance','anio'=>2025,'precio'=>200000.00,'descripcion'=>'El Mercedes-AMG GT 63 S E Performance (4 puertas) es un híbrido enchufable de alto rendimiento que combina un motor V8 biturbo de 4.0L con un motor eléctrico trasero, entregando una potencia combinada de hasta 843 CV.','marca_id'=>16,'potencia'=>843,'par_motor'=>1470,'velocidad_max'=>316,'aceleracion'=>2.9,'combustible'=>'Híbrido','transmision'=>'Automática (AMG SPEEDSHIFT MCT 9G)','traccion'=>'AWD (4MATIC+)','num_plazas'=>4,'num_puertas'=>4,'tipo_carroceria'=>'Berlina / Coupé 4 puertas','color'=>'Green Hell Magno','disponible'=>true,'destacado'=>false],

            // ── BUGATTI ──────────────────────────────────────────────────────
            ['id'=>87,'modelo'=>'Bugatti Bolide','anio'=>2020,'precio'=>4000000.00,'descripcion'=>'El Bugatti Bolide es un hiperdeportivo de circuito extremo, limitado a 40 unidades, diseñado para maximizar el rendimiento con un motor W16 de 8.0 litros y 1850 CV. Logra una velocidad superior a 500 km/h.','marca_id'=>17,'potencia'=>1850,'par_motor'=>1850,'velocidad_max'=>500,'aceleracion'=>2.2,'combustible'=>'Gasolina','transmision'=>'Automática (Doble embrague 7 vel.)','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé (Circuito)','color'=>'French Racing Blue / Carbon','disponible'=>true,'destacado'=>true],
            ['id'=>88,'modelo'=>'Bugatti Chiron Super Sport 300+','anio'=>2019,'precio'=>5400000.00,'descripcion'=>'El Bugatti Chiron Super Sport 300+ es un hiperdeportivo de producción limitada (30 unidades) diseñado para la velocidad extrema, famoso por romper la barrera de las 300 mph (490.48 km/h en 2019).','marca_id'=>17,'potencia'=>1600,'par_motor'=>1600,'velocidad_max'=>490,'aceleracion'=>2.3,'combustible'=>'Gasolina','transmision'=>'Automática (Doble embrague 7 vel.)','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Black Carbon / Jet Orange','disponible'=>false,'destacado'=>false],
            ['id'=>89,'modelo'=>'Bugatti Chiron','anio'=>2016,'precio'=>3000000.00,'descripcion'=>'El Bugatti Chiron es un superdeportivo biplaza de lujo, sucesor del Veyron, presentado en 2016 con un motor W16 de 8.0 litros y cuatro turbos que genera 1.500 CV. Alcanza velocidades superiores a 420 km/h.','marca_id'=>17,'potencia'=>1500,'par_motor'=>1600,'velocidad_max'=>420,'aceleracion'=>2.4,'combustible'=>'Gasolina','transmision'=>'Automática (Doble embrague 7 vel.)','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Atlantic Blue','disponible'=>true,'destacado'=>false],
            ['id'=>90,'modelo'=>'Bugatti La Voiture Noire','anio'=>2019,'precio'=>25000000.00,'descripcion'=>'El Bugatti La Voiture Noire es un hiperdeportivo único (one-off) y exclusivo, creado para celebrar el 110 aniversario de la marca. Inspirado en el legendario Type 57 SC Atlantic de Jean Bugatti.','marca_id'=>17,'potencia'=>1500,'par_motor'=>1600,'velocidad_max'=>420,'aceleracion'=>2.4,'combustible'=>'Gasolina','transmision'=>'Automática (Doble embrague 7 vel.)','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Deep Black Gloss','disponible'=>true,'destacado'=>false],
            ['id'=>91,'modelo'=>'Bugatti Veyron Grand Sport Vitesse La Finale','anio'=>2015,'precio'=>2500000.00,'descripcion'=>'El Bugatti Veyron Grand Sport Vitesse La Finale (2015) es la unidad 450 y última del Veyron, celebrando el fin de su producción. Basado en el Grand Sport Vitesse, monta un motor W16 8.0L con 1.200 CV y 1.500 Nm de par.','marca_id'=>17,'potencia'=>1200,'par_motor'=>1500,'velocidad_max'=>410,'aceleracion'=>2.6,'combustible'=>'Gasolina','transmision'=>'Automática (Doble embrague 7 vel.)','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Cabrio','color'=>'Italian Red / Black Carbon','disponible'=>true,'destacado'=>false],
            ['id'=>92,'modelo'=>'Bugatti Centodieci','anio'=>2020,'precio'=>15000000.00,'descripcion'=>'El Bugatti Centodieci es un hiperdeportivo exclusivo limitado a solo 10 unidades, creado como tributo al Bugatti EB110 de 1991 para celebrar el 110 aniversario de la marca. Cuenta con un motor W16 de 8.0 litros potenciado a 1.600 CV.','marca_id'=>17,'potencia'=>1600,'par_motor'=>1600,'velocidad_max'=>380,'aceleracion'=>2.4,'combustible'=>'Gasolina','transmision'=>'Automática (Doble embrague 7 vel.)','traccion'=>'AWD','num_plazas'=>2,'num_puertas'=>2,'tipo_carroceria'=>'Coupé','color'=>'Bianco','disponible'=>true,'destacado'=>false],
        ];

        // Añadimos timestamps a todos
        $now = now();
        foreach ($coches as &$c) {
            $c['created_at'] = $now;
            $c['updated_at'] = $now;
        }

        DB::table('coches')->insert($coches);
    }
}