<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MarcasSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('marcas')->insert([
            [
                'id'             => 4,
                'nombre'         => 'Lamborghini',
                'imagen_hero'    => 'marcas/lamborghini/hero.png',
                'slogan'         => 'Driving Humans Beyond',
                'anio_fundacion' => 1963,
                'pais'           => 'Italia',
                'descripcion'    => 'Automobili Lamborghini (fundada en 1963 por Ferruccio Lamborghini en Sant\'Agata Bolognese, Italia) es un fabricante icónico de superdeportivos de lujo reconocidos por su diseño radical, ángulos afilados, alto rendimiento y motores V12. La marca, parte del Grupo Volkswagen, encarna la fuerza y la pasión con su logo del toro, destacando por modelos como el Miura, Countach, Aventador y Urus.',
                'logo'           => 'logos/lamborghini.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 8,
                'nombre'         => 'BMW',
                'imagen_hero'    => 'marcas/bmw/hero.png',
                'slogan'         => 'El placer de conducir',
                'anio_fundacion' => 1916,
                'pais'           => 'Alemania',
                'descripcion'    => 'BMW (Bayerische Motoren Werke), fundada en 1916 en Alemania, es un fabricante líder de automóviles y motocicletas de lujo, conocido por su ingeniería de precisión, diseño deportivo y alto rendimiento. Con sede en Múnich, el grupo también es dueño de Mini y Rolls-Royce, destacando por la innovación constante en su gama de vehículos.',
                'logo'           => 'logos/bmw.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 9,
                'nombre'         => 'McLaren',
                'imagen_hero'    => 'marcas/mclaren/hero.png',
                'slogan'         => 'Fearlessly Forward',
                'anio_fundacion' => 1963,
                'pais'           => 'Reino Unido',
                'descripcion'    => 'McLaren es un reconocido fabricante británico de automóviles superdeportivos y de lujo, además de una escudería histórica de Fórmula 1 fundada en 1963 por Bruce McLaren. Conocidos por su ingeniería de precisión y alto rendimiento, utilizan tecnologías derivadas de las carreras, incluyendo chasis monocasco de fibra de carbono.',
                'logo'           => 'logos/mclaren.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 10,
                'nombre'         => 'Porsche',
                'imagen_hero'    => 'marcas/porsche/hero.png',
                'slogan'         => 'Porsche, there is no substitute',
                'anio_fundacion' => 1931,
                'pais'           => 'Alemania',
                'descripcion'    => 'Porsche es una marca alemana de automóviles de lujo fundada en 1931 por Ferdinand Porsche, reconocida mundialmente por su excelencia en ingeniería, alto rendimiento y diseño deportivo. Famosa por el icónico Porsche 911, la marca combina tradición, motor bóxer y versatilidad con modelos modernos como el eléctrico Taycan, SUV (Cayenne/Macan) y sedanes.',
                'logo'           => 'logos/porsche.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 11,
                'nombre'         => 'Audi',
                'imagen_hero'    => 'marcas/audi/hero.png',
                'slogan'         => 'A la vanguardia de la técnica',
                'anio_fundacion' => 1909,
                'pais'           => 'Alemania',
                'descripcion'    => 'Audi es un prestigioso fabricante alemán de automóviles de lujo y alto rendimiento, fundado en 1909 por August Horch y parte del Grupo Volkswagen desde 1965. Su sede está en Ingolstadt, Alemania. Los cuatro aros representan la fusión de cuatro marcas en 1932: Audi, Horch, DKW y Wanderer.',
                'logo'           => 'logos/audi.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 12,
                'nombre'         => 'Pagani',
                'imagen_hero'    => 'marcas/pagani/hero.png',
                'slogan'         => 'Arte y Ciencia',
                'anio_fundacion' => 1992,
                'pais'           => 'Italia',
                'descripcion'    => 'Pagani es un fabricante italiano de superdeportivos de lujo y alto rendimiento, fundado en 1992 por el argentino-italiano Horacio Pagani en San Cesario sul Panaro, cerca de Módena. Reconocida mundialmente, la marca combina arte, ingeniería avanzada y fibra de carbono en modelos exclusivos y emblemáticos como el Zonda y el Huayra.',
                'logo'           => 'logos/pagani.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 13,
                'nombre'         => 'Ferrari',
                'imagen_hero'    => 'marcas/ferrari/hero.png',
                'slogan'         => 'Somos la competencia',
                'anio_fundacion' => 1947,
                'pais'           => 'Italia',
                'descripcion'    => 'Ferrari es un fabricante italiano de automóviles superdeportivos de lujo y competición, fundado en 1929 por Enzo Ferrari en Maranello. Reconocida mundialmente por su logo del Cavallino Rampante, es conocida por sus motores V12 de alto rendimiento, su color rojo distintivo y su éxito en la Fórmula 1.',
                'logo'           => 'logos/ferrari.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 14,
                'nombre'         => 'Toyota',
                'imagen_hero'    => 'marcas/toyota/hero.png',
                'slogan'         => 'Let\'s Go Places',
                'anio_fundacion' => 1937,
                'pais'           => 'Japón',
                'descripcion'    => 'Toyota Motor Corporation es una multinacional japonesa líder automotriz, fundada en 1937 por Kiichiro Toyoda con sede en Toyota City. Reconocida por su fiabilidad e innovación, es uno de los mayores fabricantes mundiales, pionera en tecnología híbrida y comprometida con la neutralidad de carbono.',
                'logo'           => 'logos/toyota.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 15,
                'nombre'         => 'Nissan',
                'imagen_hero'    => 'marcas/nissan/hero.png',
                'slogan'         => 'Innovation that excites',
                'anio_fundacion' => 1933,
                'pais'           => 'Japón',
                'descripcion'    => 'Nissan Motor Co., Ltd. es un destacado fabricante japonés de automóviles con sede en Yokohama, reconocido mundialmente por su innovación, ingeniería y tecnología, incluyendo sus motores e-POWER y vehículos eléctricos. Forma parte de la alianza Renault-Nissan-Mitsubishi.',
                'logo'           => 'logos/nissan.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 16,
                'nombre'         => 'Mercedes-Benz',
                'imagen_hero'    => 'marcas/mercedes/hero.png',
                'slogan'         => 'Das Beste oder nichts',
                'anio_fundacion' => 1926,
                'pais'           => 'Alemania',
                'descripcion'    => 'Mercedes-Benz es una marca alemana icónica de automóviles de lujo, vehículos comerciales y alto rendimiento, fundada en 1926 por pioneros como Karl Benz y Gottlieb Daimler. Reconocida por su lema "lo mejor o nada", se destaca por la innovación en seguridad, diseño sofisticado y tecnología avanzada.',
                'logo'           => 'logos/mercedes.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 17,
                'nombre'         => 'Bugatti',
                'imagen_hero'    => 'marcas/bugatti/hero.png',
                'slogan'         => 'Create the Incomparable',
                'anio_fundacion' => 1909,
                'pais'           => 'Francia',
                'descripcion'    => 'Bugatti es una marca francesa de hiperdeportivos de ultra lujo y alto rendimiento, fundada en 1909 por Ettore Bugatti en Molsheim. Es reconocida mundialmente por fusionar ingeniería avanzada con arte, produciendo vehículos exclusivos y extremadamente rápidos como los famosos Veyron y Chiron.',
                'logo'           => 'logos/bugatti.png',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}